MCKIN-23599 Automating ooyala xblock extraction process in PO file
edx-solutions/xblock-ooyala pull request #119
Opened 2020-08-27 12:20 UTC by wasifarbisoft

2020-08-27 17:24 UTC, naeem91 requested changes

2020-08-27 17:24 UTC, naeem91 commented on Makefile
> +extract_translations: ## extract strings to be translated, outputting .po files
Please add instructions in readme file for extracting translations. Same as https://github.com/open-craft/xblock-chat#translation-i18n

2020-08-27 17:24 UTC, naeem91 commented on requirements.txt
> +django-appconf==1.0.4; python_version > '2.7'
These requirements are not meant for default installation so should be part of a separate requirements file e.g; `requirements-dev` etc. Also `Django` will be needed

2020-08-28 06:31 UTC, wasifarbisoft commented
@naeem91 
Pull Request is ready for another round of review.

2020-08-31 08:41 UTC, naeem91 approved these changes
LGTM. Just a minor readme change.

2020-08-31 08:41 UTC, naeem91 commented on README.md
> +  3. Clone `en` directory to `ooyala_player/translations/<lang_code>/` for example: `problem_builder/translations/fa_IR/`
Change `problem_builder` to `ooyala_player/`

2020-09-01 09:24 UTC, msaqib52 approved these changes

2020-09-02 06:16 UTC, merged